### ISSUE TITLE
Proposal: let the client specify an `io.Writer` instead of assuming `os.Stdout`

### ISSUE THREAD

**Issue by allonhadaya** [go-mix/mix#55]
Hello, this looks like a very cool library. I'm excited to jump in and play with it.

Would it be a good idea to let the client choose their own `io.Writer` for audio data to be written to. It would be nice to let the client flexibly stream over tcp / write to file / pipe to another process all using the same underlying mixing implementation with different writers.

It does seem like it would require a change to the public interface, so that's something to consider.

Thoughts?

**Comment by charneykaye** [comment]
Thanks for checking it out! I've been kicking the tires with this a lot, and really enjoy using it for music projects. 

I like this feature a lot. Actually, the _only_ case I've been actually using so far is `stdout`. I run Ubuntu/Debian Linux and listen to my programs output `| aplay` or write them to a `> file`. For reasons of long-term upkeep/time-cost/distraction I have been considering deprecating the hardware bindings entirely.

To your point re: tcp, I dream about projects that might perform mixing operations in network/virtual environments for public listening..

Please suggest an interface, or the next time I work on this library I'll think about it myself..

**Comment by charneykaye** [comment]
Note in the leading branch, there is no hardware output binding: https://godoc.org/github.com/go-mix/mix

However in the last major release, there is: https://godoc.org/gopkg.in/mix.v0

It is my intention that the next release will include this feature, and be released as https://godoc.org/gopkg.in/mix.v1 -- ergo changes in the public interface are OK

**Comment by charneykaye** [comment]
I've reorganized the project around the next milestone, which I reckon to be [1.0.0](https://github.com/go-mix/mix/milestones/1.0.0) and expect  to include updates to the public interface.

Please also suggest anything else you believe essential in this release. Thanks!

**Comment by charneykaye** [comment]
Also please _do_ feel free to challenge the way the library was originally organized into these two separate packages:

``` golang
  "github.com/go-mix/mix"
  "github.com/go-mix/mix/bind"
```

I haven't thought it entirely though yet, but I want to be certain that it is still appropriate. It was originally designed this way because of some limitations of using the hardware binding libraries, e.g. SDL2 and Portaudio. Now, I can't think of a reason offhand why it needs to be this complex.

**Comment by haswalt** [comment]
#57 Should help
